import SYSTEM from '../system.es';

export default {
  ID: 'ID',
  TYPE: 'Tipo',
  DETAILS: 'Detalles',
  LOCATION: 'Ubicación',
  CITY: 'Ciudad',
  COUNTRY: 'País',
  OWNER_STATUS: 'Disponibilidad',
  REVIEW_STATUS: 'Revisión',
  ACTIONS: 'Acciones',
  MY_PLACEMENTS: 'Mis espacios',
  REVIEW_PLACEMENTS: 'Revisar espacios',
  PAUSE: 'Pausar',
  RESUME: 'Reactivar',
  WITHDRAW: 'Retirar',
  RESTORE: 'Restaurar y enviar a revisión',
  WITHDRAW_CONFIRM: 'Este espacio dejará de mostrarse de inmediato. Se conservarán sus datos y caras. ¿Quieres retirarlo?',
  SEND_FOR_REVIEW: 'Enviar a revisión',
  VISIBILITY: 'Visibilidad',
  SEARCH_PLACEMENT: 'Buscar por código',
  PENDING: 'Pendiente',
  ACTIVE: 'Activo',
  PAUSED: 'Pausado',
  WITHDRAWN: 'Retirado',
  DRAFT: 'Borrador',
  IN_REVIEW: 'En revisión',
  APPROVED: 'Aprobado',
  SUSPENDED: 'Suspendido',
  REJECTED: 'Rechazado',
  PRIVATE: 'Privado',
  PUBLIC: 'Público',
  UNLISTED: 'Oculto',
  SEARCH_BY_ID: 'Buscar por ID',
  FIND_ON_MAP: 'Buscar en el mapa',
  ...SYSTEM.PLACEMENT.TYPES
};
