import SYSTEM from '../system.en';

export default {
  ID: 'ID',
  TYPE: 'Type',
  DETAILS: 'Details',
  LOCATION: 'Location',
  CITY: 'City',
  COUNTRY: 'Country',
  OWNER_STATUS: 'Availability',
  REVIEW_STATUS: 'Review',
  ACTIONS: 'Actions',
  EDIT: 'Edit',
  PAUSE: 'Pause',
  RESUME: 'Resume',
  WITHDRAW: 'Withdraw',
  WITHDRAW_CONFIRM: 'This placement will disappear from public listings immediately. Its data and faces will be kept. Withdraw it?',
  WITHDRAW_MULTIPLE_CONFIRM: 'These {count} placements will disappear from public listings immediately. Their data and faces will be kept. Withdraw them?',
  SEND_FOR_REVIEW: 'Submit for review',
  VISIBILITY: 'Visibility',
  SEARCH_PLACEMENT: 'Search by code',
  PENDING: 'Pending',
  ACTIVE: 'Active',
  PAUSED: 'Paused',
  WITHDRAWN: 'Withdrawn',
  DRAFT: 'Draft',
  IN_REVIEW: 'In review',
  APPROVED: 'Approved',
  SUSPENDED: 'Suspended',
  REJECTED: 'Rejected',
  PRIVATE: 'Private',
  PUBLIC: 'Public',
  UNLISTED: 'Hidden',
  SEARCH_BY_ID: 'Search by ID',
  FIND_ON_MAP: 'Search on map',
  ...SYSTEM.PLACEMENT.TYPES
};
